### ISSUE TITLE
"SyntaxError: Unexpected reserved word" when running with all dependences

### ISSUE THREAD

**Issue by AustinBZechar** [The-Studio-io/xDAI-Discord-bot#8]
hello,

I made sure to install everything needed via npm, but I get a "SyntaxError: Unexpected reserved word" at line 321 when running. Could I get some help?

Thanks
Zephyr

**Comment by rabTAI** [comment]
Sorry on my phone, can you please paste that line (like 321) or provide more error info?

**Comment by AustinBZechar** [comment]
hello, here is the error info & the line.

SyntaxError: Unexpected reserved word
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)

line:  for await (const member of members){//Loop throught all the members

Thanks
Zephyr

**Comment by mittalyashu** [comment]
Seems like the problem is originating from line number https://github.com/The-Studio-io/xDAI-Discord-bot/blob/master/main.js#L321 🤔

**Comment by mittalyashu** [comment]
@NotZephyrDev Is your redis instance running?

If you running this locally, trying commenting out [these lines of code](https://github.com/The-Studio-io/xDAI-Discord-bot/blob/master/main.js#L318-L363) and then try again.

**Comment by AustinBZechar** [comment]
hello,

I think it is. I'll try to comment those lines out

Thanks
zephyr

**Comment by davecraige** [comment]
@NotZephyrDev thanks for joining us and making an issue 😀🙌

**Comment by mittalyashu** [comment]
@NotZephyrDev Can you confirm that the problem you was facing is resolved?

**Comment by AustinBZechar** [comment]
hello, sorry I didn't have time to test but I will test now

**Comment by AustinBZechar** [comment]
hello,

now I get this error code.

`});
 ^
SyntaxError: Unexpected token )
    at createScript (vm.js:53:10)
    at Object.runInThisContext (vm.js:95:10)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
`

Thanks
Austin

**Comment by mittalyashu** [comment]
@rabTAI Can you take a look at this?
